[package]
name = "grrs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
assert_cmd = "2.1.0"
assert_fs = "1.1.3"
clap = { version = "4.5.50", features = ["derive"] }
predicates = "3.1.3"
